/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace EZTutor.Data.Local.Entities
{
    /// <summary>
    /// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
    /// </summary>
    [Serializable]
    public class Slides 
    {
        #region Private Members
		
        // Variabili di stato
        private bool _isChanged;
        private bool _isDeleted;

        // Primary Key(s) 
        private Guid _slideid; 
		
        // Properties 
        private string _slidename; 
        private Guid _lectureid; 
        private Guid _topicid; 		

        #endregion
		
        #region Default ( Empty ) Class Constructor
		
        /// <summary>
        /// default constructor
        /// </summary>
        public Slides()
        {
            _slideid = Guid.NewGuid(); 
            _slidename = ""; 
            _lectureid = Guid.Empty; 
            _topicid = Guid.Empty; 
        }
		
        #endregion // End of Default ( Empty ) Class Constructor
		
        #region Full Constructor
		
        /// <summary>
        /// full constructor
        /// </summary>
        public Slides(Guid slideid, string slidename, Guid lectureid, Guid topicid)
        {
            _slideid = slideid; 
            _slidename = slidename; 
            _lectureid = lectureid; 
            _topicid = topicid; 
        }
		
        #endregion // End Full Constructor

        #region Public Properties
			
        /// <summary>
        /// 
        /// </summary>		
        public virtual Guid Slideid
        {
            get { return _slideid; }
            set { _isChanged |= (_slideid != value); _slideid = value; }
        } 
	  
        /// <summary>
        /// 
        /// </summary>		
        public virtual string SlideName
        {
            get { return _slidename; }
            set { _isChanged |= (_slidename != value); _slidename = value; }
        } 
	  
        /// <summary>
        /// 
        /// </summary>		
        public virtual Guid Lectureid
        {
            get { return _lectureid; }
            set { _isChanged |= (_lectureid != value); _lectureid = value; }
        } 
	  
        /// <summary>
        /// 
        /// </summary>		
        public virtual Guid Topicid
        {
            get { return _topicid; }
            set { _isChanged |= (_topicid != value); _topicid = value; }
        } 
	  
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsChanged
        {
            get { return _isChanged; }
        }
		
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsDeleted
        {
            get { return _isDeleted; }
        }
		
        #endregion 
		
        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public virtual void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }
		
        #endregion
		
        #region Equals And HashCode Overrides
		
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals( object obj )
        {
            if( this == obj ) return true;
            if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
            Slides castObj = (Slides)obj; 
            return ( castObj != null ) &&
                   ( this._slideid == castObj.Slideid );
        }
		
        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        { 
            int hash = 57; 
            hash = 27 * hash * this._slideid.GetHashCode();
					
            return hash;		
			
        }
		
        #endregion
		
    }
}