/*

insert license info here

*/

using System;
using System.Collections;
using System.Collections.Generic;


namespace EZTutor.Data.Local.Entities
{
    /// <summary>
    /// Generated by MyGeneration using the NHibernate Object Mapping 1.3.1 by Grimaldi Giuseppe (giuseppe.grimaldi@infracom.it)
    /// </summary>
    [Serializable]
    public class Lectures 
    {
        #region Private Members
		
        // Variabili di stato
        private bool _isChanged;
        private bool _isDeleted;

        // Primary Key(s) 
        private Guid _lectureid; 
		
        // Properties 
        private string _lecturename; 
        private int _lectureweek; 		

        #endregion
		
        #region Default ( Empty ) Class Constructor
		
        /// <summary>
        /// default constructor
        /// </summary>
        public Lectures()
        {
            _lectureid = Guid.NewGuid(); 
            _lecturename = ""; 
            _lectureweek = 0; 
        }
		
        #endregion // End of Default ( Empty ) Class Constructor
		
        #region Full Constructor
		
        /// <summary>
        /// full constructor
        /// </summary>
        public Lectures(Guid lectureid, string lecturename, int lectureweek)
        {
            _lectureid = lectureid; 
            _lecturename = lecturename; 
            _lectureweek = lectureweek; 
        }
		
        #endregion // End Full Constructor

        #region Public Properties
			
        /// <summary>
        /// 
        /// </summary>		
        public virtual Guid Lectureid
        {
            get { return _lectureid; }
            set { _isChanged |= (_lectureid != value); _lectureid = value; }
        } 
	  
        /// <summary>
        /// 
        /// </summary>		
        public virtual string LectureName
        {
            get { return _lecturename; }
            set { _isChanged |= (_lecturename != value); _lecturename = value; }
        } 
	  
        /// <summary>
        /// 
        /// </summary>		
        public virtual int LectureWeek
        {
            get { return _lectureweek; }
            set { _isChanged |= (_lectureweek != value); _lectureweek = value; }
        } 
	  
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsChanged
        {
            get { return _isChanged; }
        }
		
        /// <summary>
        /// Returns whether or not the object has changed it's values.
        /// </summary>
        public virtual bool IsDeleted
        {
            get { return _isDeleted; }
        }
		
        #endregion 
		
        #region Public Functions

        /// <summary>
        /// mark the item as deleted
        /// </summary>
        public virtual void MarkAsDeleted()
        {
            _isDeleted = true;
            _isChanged = true;
        }
		
        #endregion
		
        #region Equals And HashCode Overrides
		
        /// <summary>
        /// local implementation of Equals based on unique value members
        /// </summary>
        public override bool Equals( object obj )
        {
            if( this == obj ) return true;
            if( ( obj == null ) || ( obj.GetType() != this.GetType() ) ) return false;
            Lectures castObj = (Lectures)obj; 
            return ( castObj != null ) &&
                   ( this._lectureid == castObj.Lectureid );
        }
		
        /// <summary>
        /// local implementation of GetHashCode based on unique value members
        /// </summary>
        public override int GetHashCode()
        { 
            int hash = 57; 
            hash = 27 * hash * this._lectureid.GetHashCode();
					
            return hash;		
			
        }
		
        #endregion
		
    }
}